# Generated by Django 5.2.17 on 2026-08-25 19:26

import apps.signalements.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vol", "Vol"),
                            ("agression", "Agression"),
                            ("cybermenace", "Cybermenace"),
                            ("arnaque", "Arnaque"),
                            ("abus", "Abus d'autorite"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("lieu", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.signalements.models.signalement_photo_path,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en attente", "En attente"),
                            ("en cours", "En cours"),
                            ("traite", "Traite"),
                        ],
                        default="en attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "signalement",
                "verbose_name_plural": "signalements",
                "ordering": ["-created_at"],
            },
        ),
    ]
