# Generated by Django 5.2.17 on 2026-08-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointAccueil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=255)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("contact", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "point d'accueil",
                "verbose_name_plural": "points d'accueil",
                "db_table": "points_accueil",
                "ordering": ["ville", "nom"],
            },
        ),
    ]
