# Generated by Django 5.2.17 on 2026-08-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conseil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("famille", "Famille"),
                            ("numerique", "Numerique"),
                            ("habitation", "Habitation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("theme", models.CharField(blank=True, max_length=255, null=True)),
                ("contenu", models.TextField()),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "conseil",
                "verbose_name_plural": "conseils",
                "ordering": ["-date_publication", "-created_at"],
            },
        ),
    ]
