# Generated by Django 5.2.17 on 2026-08-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("ville", models.CharField(max_length=255)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("alerte", "Alerte"),
                            ("urgence", "Urgence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "alerte",
                "verbose_name_plural": "alertes",
                "ordering": ["-date_publication", "-created_at"],
            },
        ),
    ]
